version: "3.3"
services:
  cowin:
    build: .
    container_name: cowin_bot
    restart: always
    environment:
      - EMAIL_USER
      - EMAIL_PASSWORD
      - MAILING_LIST
      - TWITTER_API_CONSUMER_KEY
      - TWITTER_API_CONSUMER_SECRET
      - TWITTER_API_ACCESS_TOKEN
      - TWITTER_API_ACCESS_TOKEN_SECRET
      - TWITTER_BEARER_TOKEN